/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as EnRouteImport } from './routes/en'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtikelIndexRouteImport } from './routes/artikel/index'
import { Route as ArtikelSlugRouteImport } from './routes/artikel/$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRoute = EnRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtikelIndexRoute = ArtikelIndexRouteImport.update({
  id: '/artikel/',
  path: '/artikel/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtikelSlugRoute = ArtikelSlugRouteImport.update({
  id: '/artikel/$slug',
  path: '/artikel/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/en': typeof EnRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/artikel/$slug': typeof ArtikelSlugRoute
  '/artikel/': typeof ArtikelIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/en': typeof EnRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/artikel/$slug': typeof ArtikelSlugRoute
  '/artikel': typeof ArtikelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/en': typeof EnRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/artikel/$slug': typeof ArtikelSlugRoute
  '/artikel/': typeof ArtikelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/en' | '/sitemap.xml' | '/artikel/$slug' | '/artikel/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/en' | '/sitemap.xml' | '/artikel/$slug' | '/artikel'
  id: '__root__' | '/' | '/en' | '/sitemap.xml' | '/artikel/$slug' | '/artikel/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EnRoute: typeof EnRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ArtikelSlugRoute: typeof ArtikelSlugRoute
  ArtikelIndexRoute: typeof ArtikelIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artikel/': {
      id: '/artikel/'
      path: '/artikel'
      fullPath: '/artikel/'
      preLoaderRoute: typeof ArtikelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artikel/$slug': {
      id: '/artikel/$slug'
      path: '/artikel/$slug'
      fullPath: '/artikel/$slug'
      preLoaderRoute: typeof ArtikelSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EnRoute: EnRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ArtikelSlugRoute: ArtikelSlugRoute,
  ArtikelIndexRoute: ArtikelIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
