/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RiwayatRouteImport } from './routes/riwayat'
import { Route as InfoRouteImport } from './routes/info'
import { Route as EnRouteImport } from './routes/en'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtikelIndexRouteImport } from './routes/artikel/index'
import { Route as EnRiwayatRouteImport } from './routes/en.riwayat'
import { Route as EnInfoRouteImport } from './routes/en.info'
import { Route as ArtikelSlugRouteImport } from './routes/artikel/$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RiwayatRoute = RiwayatRouteImport.update({
  id: '/riwayat',
  path: '/riwayat',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoRoute = InfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRoute = EnRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtikelIndexRoute = ArtikelIndexRouteImport.update({
  id: '/artikel/',
  path: '/artikel/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRiwayatRoute = EnRiwayatRouteImport.update({
  id: '/riwayat',
  path: '/riwayat',
  getParentRoute: () => EnRoute,
} as any)
const EnInfoRoute = EnInfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => EnRoute,
} as any)
const ArtikelSlugRoute = ArtikelSlugRouteImport.update({
  id: '/artikel/$slug',
  path: '/artikel/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/en': typeof EnRouteWithChildren
  '/info': typeof InfoRoute
  '/riwayat': typeof RiwayatRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/artikel/$slug': typeof ArtikelSlugRoute
  '/en/info': typeof EnInfoRoute
  '/en/riwayat': typeof EnRiwayatRoute
  '/artikel/': typeof ArtikelIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/en': typeof EnRouteWithChildren
  '/info': typeof InfoRoute
  '/riwayat': typeof RiwayatRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/artikel/$slug': typeof ArtikelSlugRoute
  '/en/info': typeof EnInfoRoute
  '/en/riwayat': typeof EnRiwayatRoute
  '/artikel': typeof ArtikelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/en': typeof EnRouteWithChildren
  '/info': typeof InfoRoute
  '/riwayat': typeof RiwayatRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/artikel/$slug': typeof ArtikelSlugRoute
  '/en/info': typeof EnInfoRoute
  '/en/riwayat': typeof EnRiwayatRoute
  '/artikel/': typeof ArtikelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/en'
    | '/info'
    | '/riwayat'
    | '/sitemap.xml'
    | '/artikel/$slug'
    | '/en/info'
    | '/en/riwayat'
    | '/artikel/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/en'
    | '/info'
    | '/riwayat'
    | '/sitemap.xml'
    | '/artikel/$slug'
    | '/en/info'
    | '/en/riwayat'
    | '/artikel'
  id:
    | '__root__'
    | '/'
    | '/en'
    | '/info'
    | '/riwayat'
    | '/sitemap.xml'
    | '/artikel/$slug'
    | '/en/info'
    | '/en/riwayat'
    | '/artikel/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EnRoute: typeof EnRouteWithChildren
  InfoRoute: typeof InfoRoute
  RiwayatRoute: typeof RiwayatRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ArtikelSlugRoute: typeof ArtikelSlugRoute
  ArtikelIndexRoute: typeof ArtikelIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/riwayat': {
      id: '/riwayat'
      path: '/riwayat'
      fullPath: '/riwayat'
      preLoaderRoute: typeof RiwayatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info': {
      id: '/info'
      path: '/info'
      fullPath: '/info'
      preLoaderRoute: typeof InfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artikel/': {
      id: '/artikel/'
      path: '/artikel'
      fullPath: '/artikel/'
      preLoaderRoute: typeof ArtikelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/riwayat': {
      id: '/en/riwayat'
      path: '/riwayat'
      fullPath: '/en/riwayat'
      preLoaderRoute: typeof EnRiwayatRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/info': {
      id: '/en/info'
      path: '/info'
      fullPath: '/en/info'
      preLoaderRoute: typeof EnInfoRouteImport
      parentRoute: typeof EnRoute
    }
    '/artikel/$slug': {
      id: '/artikel/$slug'
      path: '/artikel/$slug'
      fullPath: '/artikel/$slug'
      preLoaderRoute: typeof ArtikelSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EnRouteChildren {
  EnInfoRoute: typeof EnInfoRoute
  EnRiwayatRoute: typeof EnRiwayatRoute
}

const EnRouteChildren: EnRouteChildren = {
  EnInfoRoute: EnInfoRoute,
  EnRiwayatRoute: EnRiwayatRoute,
}

const EnRouteWithChildren = EnRoute._addFileChildren(EnRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EnRoute: EnRouteWithChildren,
  InfoRoute: InfoRoute,
  RiwayatRoute: RiwayatRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ArtikelSlugRoute: ArtikelSlugRoute,
  ArtikelIndexRoute: ArtikelIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
